// This file is part of CORD – https://cord.network

// Copyright (C) Dhiway Networks Pvt. Ltd.
// SPDX-License-Identifier: GPL-3.0-or-later

// CORD is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

// CORD is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.

// You should have received a copy of the GNU General Public License
// along with CORD. If not, see <https://www.gnu.org/licenses/>.

//! Autogenerated weights for `pallet_registries`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 42.0.0
//! DATE: 2025-01-28, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `ns31311672`, CPU: `AMD Ryzen 5 3600X 6-Core Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// ./target/production/cord
// benchmark
// pallet
// --chain=dev
// --steps=50
// --repeat=20
// --pallet=pallet_registries
// --extrinsic=*
// --wasm-execution=compiled
// --heap-pages=4096
// --output=./pallets/registries/src/weights.rs
// --header=./HEADER-GPL3
// --template=./.maintain/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_registries`.
pub trait WeightInfo {
	fn add_delegate() -> Weight;
	fn add_admin_delegate() -> Weight;
	fn add_delegator() -> Weight;
	fn remove_delegate() -> Weight;
	fn create() -> Weight;
	fn update() -> Weight;
	fn revoke() -> Weight;
	fn reinstate() -> Weight;
	fn archive() -> Weight;
	fn restore() -> Weight;
}

/// Weights for `pallet_registries` using the CORD node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `NameSpace::Authorizations` (r:1 w:0)
	/// Proof: `NameSpace::Authorizations` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
	/// Storage: `NameSpace::NameSpaces` (r:1 w:0)
	/// Proof: `NameSpace::NameSpaces` (`max_values`: None, `max_size`: Some(500134), added: 502609, mode: `MaxEncodedLen`)
	/// Storage: `Registries::Authorizations` (r:2 w:1)
	/// Proof: `Registries::Authorizations` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
	/// Storage: `Registries::RegistryInfo` (r:1 w:0)
	/// Proof: `Registries::RegistryInfo` (`max_values`: None, `max_size`: Some(233), added: 2708, mode: `MaxEncodedLen`)
	/// Storage: `Registries::Delegates` (r:1 w:1)
	/// Proof: `Registries::Delegates` (`max_values`: None, `max_size`: Some(320068), added: 322543, mode: `MaxEncodedLen`)
	/// Storage: `Identifier::Identifiers` (r:1 w:1)
	/// Proof: `Identifier::Identifiers` (`max_values`: None, `max_size`: Some(4294967295), added: 2474, mode: `MaxEncodedLen`)
	fn add_delegate() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1464`
		//  Estimated: `503599`
		// Minimum execution time: 43_250_000 picoseconds.
		Weight::from_parts(43_921_000, 503599)
			.saturating_add(T::DbWeight::get().reads(7_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `NameSpace::Authorizations` (r:1 w:0)
	/// Proof: `NameSpace::Authorizations` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
	/// Storage: `NameSpace::NameSpaces` (r:1 w:0)
	/// Proof: `NameSpace::NameSpaces` (`max_values`: None, `max_size`: Some(500134), added: 502609, mode: `MaxEncodedLen`)
	/// Storage: `Registries::Authorizations` (r:2 w:1)
	/// Proof: `Registries::Authorizations` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
	/// Storage: `Registries::RegistryInfo` (r:1 w:0)
	/// Proof: `Registries::RegistryInfo` (`max_values`: None, `max_size`: Some(233), added: 2708, mode: `MaxEncodedLen`)
	/// Storage: `Registries::Delegates` (r:1 w:1)
	/// Proof: `Registries::Delegates` (`max_values`: None, `max_size`: Some(320068), added: 322543, mode: `MaxEncodedLen`)
	/// Storage: `Identifier::Identifiers` (r:1 w:1)
	/// Proof: `Identifier::Identifiers` (`max_values`: None, `max_size`: Some(4294967295), added: 2474, mode: `MaxEncodedLen`)
	fn add_admin_delegate() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1464`
		//  Estimated: `503599`
		// Minimum execution time: 42_900_000 picoseconds.
		Weight::from_parts(43_500_000, 503599)
			.saturating_add(T::DbWeight::get().reads(7_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `NameSpace::Authorizations` (r:1 w:0)
	/// Proof: `NameSpace::Authorizations` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
	/// Storage: `NameSpace::NameSpaces` (r:1 w:0)
	/// Proof: `NameSpace::NameSpaces` (`max_values`: None, `max_size`: Some(500134), added: 502609, mode: `MaxEncodedLen`)
	/// Storage: `Registries::Authorizations` (r:2 w:1)
	/// Proof: `Registries::Authorizations` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
	/// Storage: `Registries::RegistryInfo` (r:1 w:0)
	/// Proof: `Registries::RegistryInfo` (`max_values`: None, `max_size`: Some(233), added: 2708, mode: `MaxEncodedLen`)
	/// Storage: `Registries::Delegates` (r:1 w:1)
	/// Proof: `Registries::Delegates` (`max_values`: None, `max_size`: Some(320068), added: 322543, mode: `MaxEncodedLen`)
	/// Storage: `Identifier::Identifiers` (r:1 w:1)
	/// Proof: `Identifier::Identifiers` (`max_values`: None, `max_size`: Some(4294967295), added: 2474, mode: `MaxEncodedLen`)
	fn add_delegator() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1464`
		//  Estimated: `503599`
		// Minimum execution time: 42_801_000 picoseconds.
		Weight::from_parts(43_620_000, 503599)
			.saturating_add(T::DbWeight::get().reads(7_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `NameSpace::Authorizations` (r:1 w:0)
	/// Proof: `NameSpace::Authorizations` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
	/// Storage: `NameSpace::NameSpaces` (r:1 w:0)
	/// Proof: `NameSpace::NameSpaces` (`max_values`: None, `max_size`: Some(500134), added: 502609, mode: `MaxEncodedLen`)
	/// Storage: `Registries::Authorizations` (r:2 w:1)
	/// Proof: `Registries::Authorizations` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
	/// Storage: `Registries::RegistryInfo` (r:1 w:0)
	/// Proof: `Registries::RegistryInfo` (`max_values`: None, `max_size`: Some(233), added: 2708, mode: `MaxEncodedLen`)
	/// Storage: `Registries::Delegates` (r:1 w:1)
	/// Proof: `Registries::Delegates` (`max_values`: None, `max_size`: Some(320068), added: 322543, mode: `MaxEncodedLen`)
	/// Storage: `Identifier::Identifiers` (r:1 w:1)
	/// Proof: `Identifier::Identifiers` (`max_values`: None, `max_size`: Some(4294967295), added: 2474, mode: `MaxEncodedLen`)
	fn remove_delegate() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1721`
		//  Estimated: `503599`
		// Minimum execution time: 43_011_000 picoseconds.
		Weight::from_parts(43_820_000, 503599)
			.saturating_add(T::DbWeight::get().reads(7_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `NameSpace::Authorizations` (r:1 w:0)
	/// Proof: `NameSpace::Authorizations` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
	/// Storage: `NameSpace::NameSpaces` (r:1 w:1)
	/// Proof: `NameSpace::NameSpaces` (`max_values`: None, `max_size`: Some(500134), added: 502609, mode: `MaxEncodedLen`)
	/// Storage: `Registries::RegistryInfo` (r:1 w:1)
	/// Proof: `Registries::RegistryInfo` (`max_values`: None, `max_size`: Some(233), added: 2708, mode: `MaxEncodedLen`)
	/// Storage: `Identifier::Identifiers` (r:1 w:1)
	/// Proof: `Identifier::Identifiers` (`max_values`: None, `max_size`: Some(4294967295), added: 2474, mode: `MaxEncodedLen`)
	/// Storage: `Registries::Delegates` (r:0 w:1)
	/// Proof: `Registries::Delegates` (`max_values`: None, `max_size`: Some(320068), added: 322543, mode: `MaxEncodedLen`)
	/// Storage: `Registries::Authorizations` (r:0 w:1)
	/// Proof: `Registries::Authorizations` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
	fn create() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `779`
		//  Estimated: `503599`
		// Minimum execution time: 36_210_000 picoseconds.
		Weight::from_parts(36_830_000, 503599)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(5_u64))
	}
	/// Storage: `NameSpace::Authorizations` (r:1 w:0)
	/// Proof: `NameSpace::Authorizations` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
	/// Storage: `NameSpace::NameSpaces` (r:1 w:0)
	/// Proof: `NameSpace::NameSpaces` (`max_values`: None, `max_size`: Some(500134), added: 502609, mode: `MaxEncodedLen`)
	/// Storage: `Registries::RegistryInfo` (r:1 w:1)
	/// Proof: `Registries::RegistryInfo` (`max_values`: None, `max_size`: Some(233), added: 2708, mode: `MaxEncodedLen`)
	/// Storage: `Registries::Authorizations` (r:1 w:0)
	/// Proof: `Registries::Authorizations` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
	/// Storage: `Identifier::Identifiers` (r:1 w:1)
	/// Proof: `Identifier::Identifiers` (`max_values`: None, `max_size`: Some(4294967295), added: 2474, mode: `MaxEncodedLen`)
	fn update() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1375`
		//  Estimated: `503599`
		// Minimum execution time: 36_291_000 picoseconds.
		Weight::from_parts(36_700_000, 503599)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `NameSpace::Authorizations` (r:1 w:0)
	/// Proof: `NameSpace::Authorizations` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
	/// Storage: `NameSpace::NameSpaces` (r:1 w:0)
	/// Proof: `NameSpace::NameSpaces` (`max_values`: None, `max_size`: Some(500134), added: 502609, mode: `MaxEncodedLen`)
	/// Storage: `Registries::Authorizations` (r:1 w:0)
	/// Proof: `Registries::Authorizations` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
	/// Storage: `Registries::RegistryInfo` (r:1 w:1)
	/// Proof: `Registries::RegistryInfo` (`max_values`: None, `max_size`: Some(233), added: 2708, mode: `MaxEncodedLen`)
	/// Storage: `Identifier::Identifiers` (r:1 w:1)
	/// Proof: `Identifier::Identifiers` (`max_values`: None, `max_size`: Some(4294967295), added: 2474, mode: `MaxEncodedLen`)
	fn revoke() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1375`
		//  Estimated: `503599`
		// Minimum execution time: 35_740_000 picoseconds.
		Weight::from_parts(36_181_000, 503599)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `NameSpace::Authorizations` (r:1 w:0)
	/// Proof: `NameSpace::Authorizations` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
	/// Storage: `NameSpace::NameSpaces` (r:1 w:0)
	/// Proof: `NameSpace::NameSpaces` (`max_values`: None, `max_size`: Some(500134), added: 502609, mode: `MaxEncodedLen`)
	/// Storage: `Registries::Authorizations` (r:1 w:0)
	/// Proof: `Registries::Authorizations` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
	/// Storage: `Registries::RegistryInfo` (r:1 w:1)
	/// Proof: `Registries::RegistryInfo` (`max_values`: None, `max_size`: Some(233), added: 2708, mode: `MaxEncodedLen`)
	/// Storage: `Identifier::Identifiers` (r:1 w:1)
	/// Proof: `Identifier::Identifiers` (`max_values`: None, `max_size`: Some(4294967295), added: 2474, mode: `MaxEncodedLen`)
	fn reinstate() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1384`
		//  Estimated: `503599`
		// Minimum execution time: 35_590_000 picoseconds.
		Weight::from_parts(36_170_000, 503599)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `NameSpace::Authorizations` (r:1 w:0)
	/// Proof: `NameSpace::Authorizations` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
	/// Storage: `NameSpace::NameSpaces` (r:1 w:0)
	/// Proof: `NameSpace::NameSpaces` (`max_values`: None, `max_size`: Some(500134), added: 502609, mode: `MaxEncodedLen`)
	/// Storage: `Registries::Authorizations` (r:1 w:0)
	/// Proof: `Registries::Authorizations` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
	/// Storage: `Registries::RegistryInfo` (r:1 w:1)
	/// Proof: `Registries::RegistryInfo` (`max_values`: None, `max_size`: Some(233), added: 2708, mode: `MaxEncodedLen`)
	/// Storage: `Identifier::Identifiers` (r:1 w:1)
	/// Proof: `Identifier::Identifiers` (`max_values`: None, `max_size`: Some(4294967295), added: 2474, mode: `MaxEncodedLen`)
	fn archive() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1375`
		//  Estimated: `503599`
		// Minimum execution time: 35_670_000 picoseconds.
		Weight::from_parts(35_981_000, 503599)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `NameSpace::Authorizations` (r:1 w:0)
	/// Proof: `NameSpace::Authorizations` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
	/// Storage: `NameSpace::NameSpaces` (r:1 w:0)
	/// Proof: `NameSpace::NameSpaces` (`max_values`: None, `max_size`: Some(500134), added: 502609, mode: `MaxEncodedLen`)
	/// Storage: `Registries::Authorizations` (r:1 w:0)
	/// Proof: `Registries::Authorizations` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
	/// Storage: `Registries::RegistryInfo` (r:1 w:1)
	/// Proof: `Registries::RegistryInfo` (`max_values`: None, `max_size`: Some(233), added: 2708, mode: `MaxEncodedLen`)
	/// Storage: `Identifier::Identifiers` (r:1 w:1)
	/// Proof: `Identifier::Identifiers` (`max_values`: None, `max_size`: Some(4294967295), added: 2474, mode: `MaxEncodedLen`)
	fn restore() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1384`
		//  Estimated: `503599`
		// Minimum execution time: 35_800_000 picoseconds.
		Weight::from_parts(36_241_000, 503599)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `NameSpace::Authorizations` (r:1 w:0)
	/// Proof: `NameSpace::Authorizations` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
	/// Storage: `NameSpace::NameSpaces` (r:1 w:0)
	/// Proof: `NameSpace::NameSpaces` (`max_values`: None, `max_size`: Some(500134), added: 502609, mode: `MaxEncodedLen`)
	/// Storage: `Registries::Authorizations` (r:2 w:1)
	/// Proof: `Registries::Authorizations` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
	/// Storage: `Registries::RegistryInfo` (r:1 w:0)
	/// Proof: `Registries::RegistryInfo` (`max_values`: None, `max_size`: Some(233), added: 2708, mode: `MaxEncodedLen`)
	/// Storage: `Registries::Delegates` (r:1 w:1)
	/// Proof: `Registries::Delegates` (`max_values`: None, `max_size`: Some(320068), added: 322543, mode: `MaxEncodedLen`)
	/// Storage: `Identifier::Identifiers` (r:1 w:1)
	/// Proof: `Identifier::Identifiers` (`max_values`: None, `max_size`: Some(4294967295), added: 2474, mode: `MaxEncodedLen`)
	fn add_delegate() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1464`
		//  Estimated: `503599`
		// Minimum execution time: 43_250_000 picoseconds.
		Weight::from_parts(43_921_000, 503599)
			.saturating_add(RocksDbWeight::get().reads(7_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `NameSpace::Authorizations` (r:1 w:0)
	/// Proof: `NameSpace::Authorizations` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
	/// Storage: `NameSpace::NameSpaces` (r:1 w:0)
	/// Proof: `NameSpace::NameSpaces` (`max_values`: None, `max_size`: Some(500134), added: 502609, mode: `MaxEncodedLen`)
	/// Storage: `Registries::Authorizations` (r:2 w:1)
	/// Proof: `Registries::Authorizations` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
	/// Storage: `Registries::RegistryInfo` (r:1 w:0)
	/// Proof: `Registries::RegistryInfo` (`max_values`: None, `max_size`: Some(233), added: 2708, mode: `MaxEncodedLen`)
	/// Storage: `Registries::Delegates` (r:1 w:1)
	/// Proof: `Registries::Delegates` (`max_values`: None, `max_size`: Some(320068), added: 322543, mode: `MaxEncodedLen`)
	/// Storage: `Identifier::Identifiers` (r:1 w:1)
	/// Proof: `Identifier::Identifiers` (`max_values`: None, `max_size`: Some(4294967295), added: 2474, mode: `MaxEncodedLen`)
	fn add_admin_delegate() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1464`
		//  Estimated: `503599`
		// Minimum execution time: 42_900_000 picoseconds.
		Weight::from_parts(43_500_000, 503599)
			.saturating_add(RocksDbWeight::get().reads(7_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `NameSpace::Authorizations` (r:1 w:0)
	/// Proof: `NameSpace::Authorizations` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
	/// Storage: `NameSpace::NameSpaces` (r:1 w:0)
	/// Proof: `NameSpace::NameSpaces` (`max_values`: None, `max_size`: Some(500134), added: 502609, mode: `MaxEncodedLen`)
	/// Storage: `Registries::Authorizations` (r:2 w:1)
	/// Proof: `Registries::Authorizations` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
	/// Storage: `Registries::RegistryInfo` (r:1 w:0)
	/// Proof: `Registries::RegistryInfo` (`max_values`: None, `max_size`: Some(233), added: 2708, mode: `MaxEncodedLen`)
	/// Storage: `Registries::Delegates` (r:1 w:1)
	/// Proof: `Registries::Delegates` (`max_values`: None, `max_size`: Some(320068), added: 322543, mode: `MaxEncodedLen`)
	/// Storage: `Identifier::Identifiers` (r:1 w:1)
	/// Proof: `Identifier::Identifiers` (`max_values`: None, `max_size`: Some(4294967295), added: 2474, mode: `MaxEncodedLen`)
	fn add_delegator() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1464`
		//  Estimated: `503599`
		// Minimum execution time: 42_801_000 picoseconds.
		Weight::from_parts(43_620_000, 503599)
			.saturating_add(RocksDbWeight::get().reads(7_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `NameSpace::Authorizations` (r:1 w:0)
	/// Proof: `NameSpace::Authorizations` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
	/// Storage: `NameSpace::NameSpaces` (r:1 w:0)
	/// Proof: `NameSpace::NameSpaces` (`max_values`: None, `max_size`: Some(500134), added: 502609, mode: `MaxEncodedLen`)
	/// Storage: `Registries::Authorizations` (r:2 w:1)
	/// Proof: `Registries::Authorizations` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
	/// Storage: `Registries::RegistryInfo` (r:1 w:0)
	/// Proof: `Registries::RegistryInfo` (`max_values`: None, `max_size`: Some(233), added: 2708, mode: `MaxEncodedLen`)
	/// Storage: `Registries::Delegates` (r:1 w:1)
	/// Proof: `Registries::Delegates` (`max_values`: None, `max_size`: Some(320068), added: 322543, mode: `MaxEncodedLen`)
	/// Storage: `Identifier::Identifiers` (r:1 w:1)
	/// Proof: `Identifier::Identifiers` (`max_values`: None, `max_size`: Some(4294967295), added: 2474, mode: `MaxEncodedLen`)
	fn remove_delegate() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1721`
		//  Estimated: `503599`
		// Minimum execution time: 43_011_000 picoseconds.
		Weight::from_parts(43_820_000, 503599)
			.saturating_add(RocksDbWeight::get().reads(7_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `NameSpace::Authorizations` (r:1 w:0)
	/// Proof: `NameSpace::Authorizations` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
	/// Storage: `NameSpace::NameSpaces` (r:1 w:1)
	/// Proof: `NameSpace::NameSpaces` (`max_values`: None, `max_size`: Some(500134), added: 502609, mode: `MaxEncodedLen`)
	/// Storage: `Registries::RegistryInfo` (r:1 w:1)
	/// Proof: `Registries::RegistryInfo` (`max_values`: None, `max_size`: Some(233), added: 2708, mode: `MaxEncodedLen`)
	/// Storage: `Identifier::Identifiers` (r:1 w:1)
	/// Proof: `Identifier::Identifiers` (`max_values`: None, `max_size`: Some(4294967295), added: 2474, mode: `MaxEncodedLen`)
	/// Storage: `Registries::Delegates` (r:0 w:1)
	/// Proof: `Registries::Delegates` (`max_values`: None, `max_size`: Some(320068), added: 322543, mode: `MaxEncodedLen`)
	/// Storage: `Registries::Authorizations` (r:0 w:1)
	/// Proof: `Registries::Authorizations` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
	fn create() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `779`
		//  Estimated: `503599`
		// Minimum execution time: 36_210_000 picoseconds.
		Weight::from_parts(36_830_000, 503599)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(5_u64))
	}
	/// Storage: `NameSpace::Authorizations` (r:1 w:0)
	/// Proof: `NameSpace::Authorizations` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
	/// Storage: `NameSpace::NameSpaces` (r:1 w:0)
	/// Proof: `NameSpace::NameSpaces` (`max_values`: None, `max_size`: Some(500134), added: 502609, mode: `MaxEncodedLen`)
	/// Storage: `Registries::RegistryInfo` (r:1 w:1)
	/// Proof: `Registries::RegistryInfo` (`max_values`: None, `max_size`: Some(233), added: 2708, mode: `MaxEncodedLen`)
	/// Storage: `Registries::Authorizations` (r:1 w:0)
	/// Proof: `Registries::Authorizations` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
	/// Storage: `Identifier::Identifiers` (r:1 w:1)
	/// Proof: `Identifier::Identifiers` (`max_values`: None, `max_size`: Some(4294967295), added: 2474, mode: `MaxEncodedLen`)
	fn update() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1375`
		//  Estimated: `503599`
		// Minimum execution time: 36_291_000 picoseconds.
		Weight::from_parts(36_700_000, 503599)
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `NameSpace::Authorizations` (r:1 w:0)
	/// Proof: `NameSpace::Authorizations` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
	/// Storage: `NameSpace::NameSpaces` (r:1 w:0)
	/// Proof: `NameSpace::NameSpaces` (`max_values`: None, `max_size`: Some(500134), added: 502609, mode: `MaxEncodedLen`)
	/// Storage: `Registries::Authorizations` (r:1 w:0)
	/// Proof: `Registries::Authorizations` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
	/// Storage: `Registries::RegistryInfo` (r:1 w:1)
	/// Proof: `Registries::RegistryInfo` (`max_values`: None, `max_size`: Some(233), added: 2708, mode: `MaxEncodedLen`)
	/// Storage: `Identifier::Identifiers` (r:1 w:1)
	/// Proof: `Identifier::Identifiers` (`max_values`: None, `max_size`: Some(4294967295), added: 2474, mode: `MaxEncodedLen`)
	fn revoke() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1375`
		//  Estimated: `503599`
		// Minimum execution time: 35_740_000 picoseconds.
		Weight::from_parts(36_181_000, 503599)
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `NameSpace::Authorizations` (r:1 w:0)
	/// Proof: `NameSpace::Authorizations` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
	/// Storage: `NameSpace::NameSpaces` (r:1 w:0)
	/// Proof: `NameSpace::NameSpaces` (`max_values`: None, `max_size`: Some(500134), added: 502609, mode: `MaxEncodedLen`)
	/// Storage: `Registries::Authorizations` (r:1 w:0)
	/// Proof: `Registries::Authorizations` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
	/// Storage: `Registries::RegistryInfo` (r:1 w:1)
	/// Proof: `Registries::RegistryInfo` (`max_values`: None, `max_size`: Some(233), added: 2708, mode: `MaxEncodedLen`)
	/// Storage: `Identifier::Identifiers` (r:1 w:1)
	/// Proof: `Identifier::Identifiers` (`max_values`: None, `max_size`: Some(4294967295), added: 2474, mode: `MaxEncodedLen`)
	fn reinstate() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1384`
		//  Estimated: `503599`
		// Minimum execution time: 35_590_000 picoseconds.
		Weight::from_parts(36_170_000, 503599)
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `NameSpace::Authorizations` (r:1 w:0)
	/// Proof: `NameSpace::Authorizations` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
	/// Storage: `NameSpace::NameSpaces` (r:1 w:0)
	/// Proof: `NameSpace::NameSpaces` (`max_values`: None, `max_size`: Some(500134), added: 502609, mode: `MaxEncodedLen`)
	/// Storage: `Registries::Authorizations` (r:1 w:0)
	/// Proof: `Registries::Authorizations` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
	/// Storage: `Registries::RegistryInfo` (r:1 w:1)
	/// Proof: `Registries::RegistryInfo` (`max_values`: None, `max_size`: Some(233), added: 2708, mode: `MaxEncodedLen`)
	/// Storage: `Identifier::Identifiers` (r:1 w:1)
	/// Proof: `Identifier::Identifiers` (`max_values`: None, `max_size`: Some(4294967295), added: 2474, mode: `MaxEncodedLen`)
	fn archive() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1375`
		//  Estimated: `503599`
		// Minimum execution time: 35_670_000 picoseconds.
		Weight::from_parts(35_981_000, 503599)
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `NameSpace::Authorizations` (r:1 w:0)
	/// Proof: `NameSpace::Authorizations` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
	/// Storage: `NameSpace::NameSpaces` (r:1 w:0)
	/// Proof: `NameSpace::NameSpaces` (`max_values`: None, `max_size`: Some(500134), added: 502609, mode: `MaxEncodedLen`)
	/// Storage: `Registries::Authorizations` (r:1 w:0)
	/// Proof: `Registries::Authorizations` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
	/// Storage: `Registries::RegistryInfo` (r:1 w:1)
	/// Proof: `Registries::RegistryInfo` (`max_values`: None, `max_size`: Some(233), added: 2708, mode: `MaxEncodedLen`)
	/// Storage: `Identifier::Identifiers` (r:1 w:1)
	/// Proof: `Identifier::Identifiers` (`max_values`: None, `max_size`: Some(4294967295), added: 2474, mode: `MaxEncodedLen`)
	fn restore() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1384`
		//  Estimated: `503599`
		// Minimum execution time: 35_800_000 picoseconds.
		Weight::from_parts(36_241_000, 503599)
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
}
